# Generated by Django 5.1.1 on 2025-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_post_updated_at_alter_about_about_us_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(choices=[('Social_media_management', 'Social Media Management'), ('google_and_meta_ads', 'Google & Meta Ads'), ('email_marketing', 'Email Marketing'), ('influencer_marketing', 'Influencer Marketing'), ('branding_and_media_buying', 'Branding & Media Buying'), ('photography_and_videography', 'Photography & Videography')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
