# Generated by Django 5.2.1 on 2025-06-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_service_description_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agency.package'),
        ),
    ]
