# Generated by Django 5.2.1 on 2025-06-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='case_study',
            field=models.FileField(blank=True, null=True, upload_to='case_studies/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='logo',
            field=models.FileField(upload_to='logos/'),
        ),
    ]
