# Generated by Django 5.1.1 on 2025-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_service_case_study_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(choices=[('Social media management', 'Social Media Management'), ('google & meta ads', 'Google & Meta Ads'), ('email marketing', 'Email Marketing'), ('influencer marketing', 'Influencer Marketing'), ('branding and media buying', 'Branding & Media Buying'), ('photography and videography', 'Photography & Videography')], max_length=50, unique=True),
        ),
    ]
