# Generated by Django 5.1.1 on 2025-06-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_package_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='package',
        ),
    ]
