# Generated by Django 5.1.1 on 2025-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_rename_name_service_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, unique=True)),
                ('owner', models.TextField(max_length=50, unique=True)),
                ('logo', models.FileField(upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='package',
        ),
        migrations.AlterField(
            model_name='service',
            name='package',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='logo',
        ),
        migrations.AddField(
            model_name='service',
            name='package_details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(blank=True, choices=[('Social media management', 'Social Media Management'), ('google & meta ads', 'Google & Meta Ads'), ('email marketing', 'Email Marketing'), ('influencer marketing', 'Influencer Marketing'), ('branding and media buying', 'Branding & Media Buying'), ('photography and videography', 'Photography & Videography')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='why_us',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='overview',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
