# Generated by Django 5.1.1 on 2025-07-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_clientlogo_remove_contact_package_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
