# Generated by Django 5.2.1 on 2025-07-08 22:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, null=True)),
                ('package_details', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package_details',
        ),
    ]
