# Generated by Django 5.2.1 on 2025-07-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_package_remove_service_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='packages',
            field=models.ManyToManyField(blank=True, to='agency.package'),
        ),
    ]
