# Generated by Django 5.2.1 on 2025-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_service_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='packages',
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='agency.service'),
        ),
    ]
