# Generated by Django 5.2.1 on 2025-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_remove_service_packages_package_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, null=True),
        ),
    ]
