# Generated by Django 5.2.1 on 2025-07-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_alter_package_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='agency.service'),
            preserve_default=False,
        ),
    ]
