# Generated by Django 5.2.1 on 2025-07-10 18:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_alter_package_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content'),
        ),
    ]
