# Generated by Django 5.2.1 on 2025-07-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('service', models.CharField(choices=[('Social media management', 'Social Media Management'), ('google & meta ads', 'Google & Meta Ads'), ('email marketing', 'Email Marketing'), ('influencer marketing', 'Influencer Marketing'), ('branding and media buying', 'Branding & Media Buying'), ('photography and videography', 'Photography & Videography')], max_length=50)),
                ('package', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
