# Generated by Django 5.2.1 on 2025-07-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_serviceinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('services', 'Services Page'), ('blog', 'Blog Page'), ('contact', 'Contact Page'), ('testimonial', 'Testimonial Page')], max_length=50, unique=True)),
                ('title', models.CharField(help_text='Meta Title for SEO and Social Media', max_length=255)),
                ('description', models.TextField(help_text='Meta Description for SEO')),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended size: 1200x630', null=True, upload_to='seo/')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
